### ISSUE TITLE
Load diag data from S3

### ISSUE THREAD

**Issue by esheehan-gsl** [NOAA-GSL/unified-graphics#80]
## Problem

We now have the application running in AWS, but it has no data to display.

## Solution

Upload sample data to S3 where the application can find and read it.

## No Gos

_Describe any features or behaviors that have been considered and rejected as out of scope for this project._

## Rabbit Holes

_Describe any solutions to problems that pose a risk to completing this project on time._

**Comment by ian-noaa** [comment]
Discussing this offline a bit - it looks like we have two options here:

## Option 1 - read the existing NetCDF from S3

We currently have our sample NetCDF data from Guoqing in S3 at: `s3://osti-modeling-dev-rtma-vis/`

It looks like we could update our code to read the NetCDF directly from S3 with Xarray: https://docs.xarray.dev/en/stable/user-guide/io.html#cloud-storage-buckets. It sounds like xarray's `open_dataset()` will now use fsspec to open object stores; it just needs config and access keys passed in. So we'd do something like:

```python
diag = xr.open_dataset(
    f"s3://osti-modeling-dev-rtma-vis/ncdiag_conv_{variable.value}_{loop.value}.nd4.2022050514",
    backend_kwargs={
        "storage_options": {"project": "<project-name>", "token": token}
    },
    engine="netCDF4",
)
```

I'd need to do a bit more research on the `backend_kwargs` needed for S3 - I cribbed that snippet from Xarray's GCP example.

This would be an intermediate step as we'd still want to convert data from NetCDF to Zarr in a pipeline and then read it from the API as Zarr. (i.e. - #67) 

## Option 2 - Create the data pipeline and read from Zarr

This option would essentially finish #67 first so that we can update the API service to read Zarr. 

-----

I'm inclined to go ahead and read directly from S3 first. We'll need to do this either way for the data pipeline in order to convert NetCDF to Zarr so it seems useful to figure out how to do that here and then be able to display data in the official app while we work on the dataset pipeline.

**Comment by esheehan-gsl** [comment]
Yeah, that seems reasonable. We can try reading the NetCDF files directly from S3. We’ll probably want to work out a way to manage config so that we can read from a local filesystem or S3 (to make development a little easier).

**Comment by ian-noaa** [comment]
That's a good point. What do you think of having the convention that `DIAG_DIR`/`FLASK_DIAG_DIR` is prepended with `s3://` or `file://` to have xarray look in a bucket or on the local filesystem?

**Comment by esheehan-gsl** [comment]
Tossing a protocol in front of the URI is a good idea. We’ll probably need additional environment variables for the AWS credentials needed to access the bucket, so we’ll have to add some logic somewhere that checks for an `s3://` protocol and retrieves the rest of the options we need.
